home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('kasusupdate', views.kasusupdate, name='kasusupdate'),
    path('info', views.info, name='info_prov')
]

hotline/urls.py
from django.urls import path

from . import views
app_name = 'hotline'

urlpatterns = [
    path('hotline', views.hotline, name='hotline'),
    path('hotline/data', views.data, name='rs_data'),
    path('saveRumahSakit', views.saveRumahSakit),
]

sharing/urls.py
from django.urls import path
from . import views

app_name = 'sharing'

urlpatterns = [
    path('sharing', views.sharing_page, name='sharing'),
    path('sharing-result', views.sharing_result, name='sharing-result'),
    path('sharing-search', views.sharing_search, name='sharing-search'),
    path('caripengalaman', views.cari_pengalaman)
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('hotline.urls')),
    path('', include('donation.urls')),
    path('', include('sharing.urls')),
    path('accounts/', include('signup.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name = "login")
]

home/models.py
from django.db import models

# Create your models here.
class subscribe_models(models.Model):
    nama = models.CharField(max_length=50)
    email = models.EmailField()

    # def __str__(self):
    #     return '%s' % self.nama

class kasus_models(models.Model):
    total = models.IntegerField()
    dirawat = models.IntegerField()
    sembuh = models.IntegerField()
    meninggal = models.IntegerField()
    update = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return '%d' % self.total

home/forms.py
from django import forms
from .models import subscribe_models, kasus_models

class form_subscribe(forms.ModelForm):
    class Meta:
        model = subscribe_models
        fields = '__all__'
    nama = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Input your name here'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'Input your e-mail here'}))

class form_kasus(forms.ModelForm):
    class Meta:
        model = kasus_models
        fields = '__all__'
    

home/views.py
from django.shortcuts import render, redirect
from .models import subscribe_models, kasus_models
from .forms import form_subscribe, form_kasus
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import JsonResponse
import json
import requests

# Create your views here.
def index(request):
    if request.method == 'POST':
        form = form_subscribe(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Thankyou for subscribe us!")

    form = form_subscribe()
    subs = subscribe_models.objects.all()
    formkasus = form_kasus()
    kasus = kasus_models.objects.all()
    context = {
        'subs': subs,
        'form' : form,
        'kasus': kasus,
        'formkasus' : formkasus,
    }
    return render(request, 'index.html' , context)

def kasusupdate(request):
    if request.method == 'POST':
        formkasus = form_kasus(request.POST)
        if formkasus.is_valid():
            if request.user.is_authenticated:
                formkasus.save()
                messages.success(request, "Update successfully.")
            else:
                return redirect('accounts/login')

    formkasus = form_kasus()
    kasus = kasus_models.objects.all()
    context = {
        'kasus': kasus,
        'formkasus' : formkasus,
    }
    return render(request, 'kasus.html' , context)

def info(request):
    lst = []
    try:
        item = request.GET['q']
    except:
        item = ""
    response = requests.get('https://api.kawalcorona.com/indonesia/provinsi/').json()
    for i in response:
        if(item.lower() in i["attributes"]["Provinsi"].lower()):
            lst.append(i["attributes"])
    # print(lst)

    return JsonResponse(lst, safe= False)

home/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'home.css' %}">
<title>COVCARE</title>
{% endblock meta %}

{% block content %}
<div id="id-jumbotron">
    <div class="jumbotron text-right">
        {% include 'navbar.html' %}
        <div class="intro">
            {% if user.is_authenticated %}
            <h1>Halo, {{user.username}}!</h2>
            {% else %}
            <h1>Pandemi COVID-19</h1>
            {% endif %}
            <p>Mari tingkatkan rasa kepeduliaan kita terhadap 
                <br>satu sama lain demi melawan COVID-19 
                <br>melalui platform COVCARE.</p>
            <a class= "btn btn-info" href="/#id-subs"><span style="font-weight: bold;">Subscription</span></a>
        </div>
    </div>
</div>
<div id="id-info">
    <div class="informasi">
        <h1>Informasi COVID-19</h1>
        <p>COVID-19 dapat tersebar melalui droplet yang dikeluarkan ketika orang terinfeksi batuk, bersin, atau menghembuskan nafas.
            Droplet ini cepat jatuh dan bertahan selama 28 hari di permukaan benda.
            Lakukan langkah berikut untuk mencegah penyebarannya.
        </p>
    </div>
    <div class="row">
        <div class="col">
            <div class="card img-card" style="width: 13rem; border-radius: 30px;">
                <div class="card-body">
                    <img src='{% static "masker.svg" %}' style="height: 70px;" class="card-img-top">
                    <p class="card- text-center pt-3">
                        Pakai Masker
                    </p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card img-card" style="width: 13rem; border-radius: 30px;">
                <div class="card-body">
                    <img src='{% static "cuci_tangan.svg" %}' style="height: 70px;" class="card-img-top">
                    <p class="card- text-center pt-3">
                        Cuci Tangan
                    </p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card img-card" style="width: 13rem; border-radius: 30px;">
                <div class="card-body">
                    <img src='{% static "berjarak.svg" %}' style="height: 70px;" class="card-img-top">
                    <p class="card- text-center pt-3">
                        Jaga Jarak
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<section id="id-kasus">
    <h1 id="total-text">Kasus COVID-19 di Indonesia</h1>
    {% for i in kasus %}
    {% if forloop.last %}
    <div class="row" style="justify-content: center;">
        <div class="card text-white bg-info mb-3" id="id-box" style="max-width: 10rem;">
            <div class="card-header">
                <h6>Terkonfirmasi</h6>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ i.total }}</h5>
            </div>
        </div>
        <div class="card text-white bg-danger mb-3" id="id-box1" style="max-width: 10rem;">
            <div class="card-header">
                <h6>Dirawat</h6>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ i.dirawat }}</h5>
            </div>
        </div>
        <div class="card text-white bg-success mb-3" id="id-box2" style="max-width: 10rem;">
            <div class="card-header">
                <h6>Sembuh</h6>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ i.sembuh }}</h5>
            </div>
        </div>
        <div class="card text-white bg-dark mb-3" id="id-box3" style="max-width: 10rem;">
            <div class="card-header">
                <h6>Meninggal</h6>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ i.meninggal }}</h5>
            </div>
        </div>
    </div>
    <div class="row" style="justify-content: center;">
        <p style="color: black;">Terakhir update: {{ i.update }}</p>
    </div>
    {% endif %}
    {% endfor %}
    <div class="btnupdate" style="text-align: center; padding-top: 10px;">
        <a class="btn btn-outline-info" href="{% url 'home:kasusupdate' %}">Klik untuk melakukan update kasus</a>
    </div>
    <br>
</div>
<div id="id-cari" style="text-align: center;">
    <h1 id="total-text">Kasus COVID-19 di Tiap Provinsi</h1>
        <input id="search" type="text" class="mt-3" placeholder="Masukkan nama provinsi"  style="width: 20vw; font-family: 'Poppins'; text-align: center;">
        <br>
        <br>
        <table id="target-ajax" border=1 style="width: 40%; justify-content: center; font-family: 'Poppins';">

        </table>
</div>
<div id="id-gejala">
    <div class="row" style="margin-bottom: 50px;">
        <div class="col d-flex justify-content-center">
            <div class="card" style="width: 60rem; border-radius: 30px; background-color: #eeeeee;">
                <div class="row">
                    <div class="col-sm-left">
                        <div class="text-title">
                            <p style="color: black; font-size: 40px; font-weight: bold;">Gejala</p>
                        </div>
                    </div>
                    <div class="col-sm-right" style="width:600px; padding: 30px;">
                        <div class="text-body">
                            <p style="color: black; font-size: 15px; text-align: left;">
                                Pada umumnya orang yang terpapar virus COVID-19 akan menunjukkan gejala pada hari
                                ke-5 hingga hari ke-14. Berikut gejala yang biasanya terjadi,
                                <br>Gejala Umum:
                            <br>1. Demam
                            <br>2. Batuk kering
                            <br>3. Merasa lelah
                            <br>
                            <br>Gejala Serius:
                            <br>1. Sesak nafas
                            <br>2. Nyeri pada dada
                            <br>3. Hilang kemampuan berbicara atau bergerak 
                            <br>
                            <br>Jika merasakan gejala diatas, segera kunjungi/hubungi rumah sakit rujukan dengan klik tombol dibawah ini.
                            <br>
                            <br>
                            <a class= "btn btn-info" href="{% url 'hotline:hotline' %}"><span style="font-weight: bold;">Hotline.</span></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="id-penanganan">
    <div class="row" style="margin-bottom: 50px;">
        <div class="col d-flex justify-content-center">
            <div class="card" style="width: 60rem; border-radius: 30px; background-color: #eeeeee;">
                <div class="row">
                    <div class="col-sm-left">
                        <div class="text-title">
                            <p style="color: black; font-size: 40px; font-weight: bold;">Penanganan</p>
                        </div>
                    </div>
                    <div class="col-sm-right" style="width:600px; padding: 30px;">
                        <div class="text-body">
                            <p style="color: black; font-size: 15px; text-align: left;">
                                Jika Anda merasa sakit, lakukan beberapa penanganan mandiri sebagai berikut,
                                <br>1. Gunakan ruangan yang terpisah dari keluarga atau kerabat
                                <br>2. Lakukan disinfeksi pada permukaan yang sering disentuh
                                <br>3. Jaga pola hidup sehat
                                <br>4. Batasi kontak sosial dengan siapapun
                                <br>
                                <br>Untuk menjaga kesehatan psikis selama terinfeksi, ceritalah kepada orang yang Anda percaya atau Anda dapat berbagi cerita dengan klik tombol dibawah ini.
                                <br>
                                <br>
                                <a class= "btn btn-info" href="{% url 'sharing:sharing' %}"><span style="font-weight: bold;">Sharing.</span></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<section id="id-subs">
    <h2>SUBSCRIBE TO COVCARE</h2>
    <form method="POST" action="#id-subs">
        {% csrf_token %}
        <table>  
            <td>{{ form }}</td>
        </table>
        {% if messages %}
        <ul style="list-style-type:none">
            {% for message in messages %}
                <li class="text-success">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <input class="btn btn-info" type="submit" value="SUBSCRIBE" style="font-weight: bold;">
    </form>
</div>
{% endblock content %}
{% block script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="{% static 'home.js' %}"></script>
{% endblock script %}

home/templates/kasus.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'kasus.css' %}">
<title>Update Kasus</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="container">
    <h1 id="total-text">Kasus COVID-19 di Indonesia</h1>
        <div class="row" style="justify-content: center;">
            {% for i in kasus %}
            {% if forloop.last %}
            <div class="card text-white bg-info mb-3" style="max-width: 10rem;">
                <div class="card-header">
                    <h6>Terkonfirmasi</h6>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ i.total }}</h5>
                </div>
            </div>
            <div class="card text-white bg-danger mb-3" style="max-width: 10rem;">
                <div class="card-header">
                    <h6>Dirawat</h6>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ i.dirawat }}</h5>
                </div>
            </div>
            <div class="card text-white bg-success mb-3" style="max-width: 10rem;">
                <div class="card-header">
                    <h6>Sembuh</h6>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ i.sembuh }}</h5>
                </div>
            </div>
            <div class="card text-white bg-dark mb-3" style="max-width: 10rem;">
                <div class="card-header">
                    <h6>Meninggal</h6>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ i.meninggal }}</h5>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% if messages %}
        <ul style="list-style-type:none">
            {% for message in messages %}
               <li class="text-success">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form method="POST" action="">
            {% csrf_token %}
            <table>  
                <td>{{ formkasus }}</td>
            </table>
        <a class= "btn btn-secondary" href="/"><span style="font-weight: bold;">back</span></a>
        <input class="btn btn-info" type="submit" value="Update" style="font-weight: bold;">
    </form>
</div>
{% endblock %}