sharing/urls.py
from django.urls import path
from . import views

app_name = 'sharing'

urlpatterns = [
    path('sharing', views.sharing_page, name='sharing'),
    path('sharing-result', views.sharing_result, name='sharing-result'),
    path('sharing-search', views.sharing_search, name='sharing-search'),
    path('caripengalaman', views.cari_pengalaman)
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('hotline.urls')),
    path('', include('donation.urls')),
    path('', include('sharing.urls')),
    path('accounts/', include('signup.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name = "login")
]

sharing/models.py
from django.db import models

# Create your models here.

AGE_CHOICES = [
        ('<14','14 tahun atau kurang'),
        ('15-49','15 sampai 49 tahun'),
        ('50-64','50 sampai 64 tahun'),
        ('>65','65 tahun atau lebih'),
        ]

GENDER_CHOICES = [
        ('laki-laki','Laki-Laki'),
        ('perempuan','Perempuan')
        ]

class Pengalaman(models.Model) :
    age = models.CharField('Berapa umur Anda?', choices=AGE_CHOICES, max_length=200, null=True)
    gender = models.CharField('Apa jenis kelamin Anda?', choices=GENDER_CHOICES, max_length=200, null=True)
    pengalaman = models.TextField('Bagikan pengalaman Anda seputar COVID-19!',null=True)

sharing/forms.py
from django import forms
from .models import Pengalaman
from django.contrib.admin import models
from .models import AGE_CHOICES, GENDER_CHOICES


class SharingForm(forms.ModelForm):

    class Meta:
        model = Pengalaman
        fields = '__all__'
        
    widgets = {
         'age':forms.Select(choices=AGE_CHOICES, attrs={'class':'form-control'}),
         'gender':forms.Select(choices=GENDER_CHOICES, attrs={'class':'form-control'}),
         'pengalaman':forms.Textarea(attrs={'class':'form-control'})
    }

sharing/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from .models import Pengalaman
from .forms import SharingForm
from django.core import serializers

# Create your views here.

def sharing_page(request):
    sharing = Pengalaman.objects.all()
    form = SharingForm()
    if request.method == 'POST':  
        forminput = SharingForm(request.POST)
        if forminput.is_valid():
            if request.user.is_authenticated:
                forminput.save()
                return redirect('/sharing-result')
            else:
                return redirect('accounts/login')
        else:
            return render(request, 'sharing-form.html', {'form':form, 'status': 'failed', 'data' : sharing})       
    else:
        current_data = Pengalaman.objects.all()
        return render(request, 'sharing-form.html', {'form':form, 'data':current_data})

def sharing_result(request):
    sharing = Pengalaman.objects.all()
    qs_json = serializers.serialize('json', sharing)
    return render(request, 'sharing-data.html',{'data':sharing, "chartData":qs_json} )

def sharing_search(request):
    pengalaman = Pengalaman.objects.all()
    response = {'form':SharingForm, 'contributors':pengalaman}
    return render(request, 'sharing-search.html',response)

def cari_pengalaman(request):
    pengalaman = Pengalaman.objects.all()
    json_pengalaman = serializers.serialize('json', pengalaman)
    return  HttpResponse(json_pengalaman, content_type='application/json')

sharing/templates/sharing-data.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Kumpulan Sharing</title>
{% endblock meta %}

{% block content %}
<div>
    {% include 'navbar.html' %}
</div>

<div class="d-flex flex-column justify-content-center align-items-center">
    <h1 id="sharing-header">Sharing</h1>
    <p class="sharing-desc">Kumpulan pengalaman masyarakat seputar COVID-19</p>
    <p class="sharing-desc">Kembali ke halaman <a href="{% url 'sharing:sharing' %}">Sharing</a></p>
    <a href="{% url 'sharing:sharing-search' %}" id="btn-result" class="btn btn-outline-primary" role="button" aria-pressed="true">Cari Pengalaman</a>  
</div>

<div class="chart-container">
    <div id="agechart"></div>
    <div id="genderchart"></div>
</div>

<div class="d-flex flex-column justify-content-center" style="padding:2rem 8rem;">
    <p style="font-size:2rem;font-weight: bold;">Pengalaman</p>
    <hr/>
    {% for field in data %}
        <p>{{field.pengalaman}}</p>
        <hr/>
    {% endfor %}
</div>
{% endblock content %}

{% block script %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
// Load google charts
google.charts.load('current', {'packages':['corechart']});
google.charts.setOnLoadCallback(drawChart);

// Draw the chart and set the chart values
function drawChart() {

var datas = JSON.parse("{{chartData|escapejs}}"); 

var count14 = datas.filter((el)=>{
    return el.fields.age==="<14"
})
var count1549 = datas.filter((el)=>{
    return el.fields.age==="15-49"
})
var count5064 = datas.filter((el)=>{
    return el.fields.age==="50-64"
})
var count65 = datas.filter((el)=>{
    return el.fields.age===">65"
})

var dataAge = google.visualization.arrayToDataTable([
  ['Age', 'Count'],
  ['14 tahun atau kurang', count14.length],
  ['15 sampai 49 tahun', count1549.length],
  ['50 sampai 64 tahun', count5064.length],
  ['65 tahun atau lebih', count65.length]
]);
var countPerempuan = datas.filter((el)=>{
    return el.fields.gender==="perempuan"
})
var countLelaki = datas.filter((el)=>{
    return el.fields.gender==="laki-laki"
})

var dataGender = google.visualization.arrayToDataTable([
  ['Gender', 'Count'],
  ['Laki-Laki', countLelaki.length],
  ['Perempuan', countPerempuan.length],
]);

  // Optional; add a title and set the width and height of the chart
  var options = {
      'title':'Range Umur', 'width':500, 'height':400,
      colors: ['#3d819b','#205f6c', '#0c484d', '#00485d']
  };

  var options2 = {
      'title':'Jenis Kelamin', 'width':500, 'height':400,
      colors: ['#20474D', '#4E8098']
  };
  
  // Display the chart inside the <div> element with id="piechart"
  var chartAge = new google.visualization.PieChart(document.getElementById('agechart'));
  var chartGender = new google.visualization.PieChart(document.getElementById('genderchart'));
  chartAge.draw(dataAge, options);
  chartGender.draw(dataGender,options2);
}
</script>
{% endblock script %}

sharing/templates/sharing-form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Sharing</title>
{% endblock meta %}

{% block content %}
<div>
  {% include 'navbar.html' %}
</div>
<style>
  textarea{
    padding:1rem;
  }
</style>
<div class="d-flex flex-column justify-content-center align-items-center">
  <h1 id="sharing-header">Sharing</h1>
    <p>Bagikan pengalaman Anda seputar COVID-19. </p>
    <p> Pengalaman Anda akan ditampilkan pada halaman 
      <a href="{% url 'sharing:sharing-result' %}">Kumpulan Sharing</a></p>
      <p>Anda bisa mencari pengalaman yang relevan pada
        halaman   <a href="{% url 'sharing:sharing-search' %}">Cari Pengalaman Sharing</a></p>
    <p class="sharing-desc">Sharing bersifat anonim.</p>
  
  <div class="dropdown my-menu"> 
    <button class="btn btn-secondary dropdown-toggle"  
            type="button"
            id="dropdownMenuButton" 
            data-toggle="dropdown" 
            aria-haspopup="true" 
            aria-expanded="false"> 
        Lihat Kumpulan Sharing
    </button> 
    <div class="dropdown-menu" 
         aria-labelledby="dropdownMenuButton"> 
        <a class="dropdown-item" 
           href="{% url 'sharing:sharing-result' %}">Secara Keseluruhan</a> 
        <a class="dropdown-item" 
           href="{% url 'sharing:sharing-search' %}">Cari Berdasarkan Keyword</a>
    </div> 
</div> 

</div>


  <form method="POST">
    {% csrf_token %}
    <div class="mr-auto ml-auto" style="width: 50%;">
        {% for field in form %}
        <div class="form-group" style="display: flex;flex-direction: column;">
            {{ field.label_tag }}
            {{ field }}
        </div>
        {% endfor %}
    <br>
    <div class="container">
        <input type="submit" value="Submit" id="btn-submit"class="btn btn-primary click">
    </div>
    </div>
    <br> <br>

</form>



{% endblock content %}

sharing/templates/sharing-search.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Cari Pengalaman Masyarakat</title>
{% endblock meta %}

{% block content %}
<div>
    {% include 'navbar.html' %}
</div>

<div class="d-flex flex-column justify-content-center align-items-center">
    <h1 id="sharing-header">Cari Pengalaman Masyarakat</h1>
    <p class="sharing-desc">Cari pengalaman masyarakat yang relevan dengan Anda di sini.</p>
    <a href="{% url 'sharing:sharing-result' %}" id="btn-result" class="btn btn-outline-primary" role="button" aria-pressed="true">Lihat Pengalaman Keseluruhan</a>  
    <input class="form-control form-inline" style="margin-top: 20px; width: 30%;"type="text" id="keyword" placeholder="Cari Pengalaman...">
    <input class="form-control form-inline btn btn-primary click" style="margin-top: 20px; width: 100px;" type="button" id="search-sharing" value="Search">    
</div>
<div class="card shadow mb-5" style="margin:5vw;">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr id="search-header">
            <th>No.</th>
            <th>Range Umur</th>
            <th>Jenis Kelamin</th>
            <th>Pengalaman</th>
          </tr>
        </thead>
        <tbody id="search-res">
          
        </tbody>
      </table>
    </div>
  </div>
</div>


{% endblock content %}



{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  $.ajax({
    method: 'GET',
    url: '/caripengalaman',
    success: function(result) {
        $('#search-res').empty();
        var res = "";
        for (let i = 0; i < result.length; i++) {
              res += ('<tr>' + '<td>' + (i+1) + '</td>')
              res += '<td>' + result[i].fields.age + '</td>' + '<td>' + result[i].fields.gender + '</td>'
              res += '<td>' + result[i].fields.pengalaman + '</td>' + '</tr>'

        }
        $('#search-res').append(res);
    }
  })

  $("#search-sharing").click(function(){
        var keyword = $("#keyword").val();
        $.ajax({
            method: 'GET',
            url: '/caripengalaman',
            success: function(result) {
                $('#search-res').empty();
                var res = "";
                for (let i = 0; i < result.length; i++) {
                    var pengalaman = result[i].fields.pengalaman.toLowerCase();
                    if (pengalaman.includes(keyword.toLowerCase())) {
                      res += ('<tr>' + '<td>' + (i+1) + '</td>')
                      res += '<td>' + result[i].fields.age + '</td>' + '<td>' + result[i].fields.gender + '</td>'
                      res += '<td>' + result[i].fields.pengalaman + '</td>' + '</tr>'
                    }
                }
                console.log(res);
                if (res.length != 0) {
                  $('#search-res').append(res);
                } else {
                  alert("Keyword tidak ditemukan!");
                }
                
            }
        })
    });
    $("#search-header").mouseover( function() {
    var x = document.getElementById("search-header");
    x.style.backgroundColor = "#00A9A5";
  });
    $("#search-header").mouseleave( function() {
    var x = document.getElementById("search-header");
    x.style.backgroundColor = "";
  });
});
</script>
{% endblock script %}