home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('kasusupdate', views.kasusupdate, name='kasusupdate'),
    path('info', views.info, name='info_prov')
]

hotline/urls.py
from django.urls import path

from . import views
app_name = 'hotline'

urlpatterns = [
    path('hotline', views.hotline, name='hotline'),
    path('hotline/data', views.data, name='rs_data'),
    path('saveRumahSakit', views.saveRumahSakit),
]

sharing/urls.py
from django.urls import path
from . import views

app_name = 'sharing'

urlpatterns = [
    path('sharing', views.sharing_page, name='sharing'),
    path('sharing-result', views.sharing_result, name='sharing-result'),
    path('sharing-search', views.sharing_search, name='sharing-search'),
    path('caripengalaman', views.cari_pengalaman)
]

signup/urls.py
from django.urls import path
from signup.views import sign_up

app_name = 'signup'

urlpatterns = [
    path('signup', sign_up, name='signup'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('hotline.urls')),
    path('', include('donation.urls')),
    path('', include('sharing.urls')),
    path('accounts/', include('signup.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name = "login")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Nunito&display=swap" rel="stylesheet">
       
        {% block meta %}
        {% endblock meta %}
    </head>

    <body style="overflow-x: hidden;">
    {% block content %}
    {% endblock content %}

    <div class = "footer">
        &copy; 2020 COVCARE ALL RIGHTS RESERVED
    </div>
    
    
    {% block script %}
    {% endblock script %}
    </body>

</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg" style="background-color: #092327;">
    <a class="navbar-brand" href="#">
        <div class ="title">
            covcare.
        </div>
    </a>
    <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'home:index' %}">
                    <div class ="navbar-item-text">
                        Home 
                    </div>
                    <span class="sr-only">
                        (current)
                    </span>
                </a>
            </li>
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'sharing:sharing' %}">
                    <div class ="navbar-item-text">
                        Sharing
                    </div>
                </a>
            </li>
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'donation:donation' %}">
                    <div class ="navbar-item-text">
                        Donation
                    </div>
                </a>
            </li>
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'hotline:hotline' %}">
                    <div class ="navbar-item-text">
                        Hotline
                    </div>
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'logout' %}">
                    <div class ="navbar-item-text">
                        Log Out
                    </div>
                </a>
            </li>
            {% else %}
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'login' %}">
                    <div class ="navbar-item-text">
                        Log In
                    </div>
                </a>
            </li>
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'signup:signup' %}">
                    <div class ="navbar-item-text">
                        Sign Up
                    </div>
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>